import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: "script",
      globals: {
        // Browser globals
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        requestAnimationFrame: "readonly",
        performance: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        Image: "readonly",
        AbortController: "readonly",
        btoa: "readonly",
        atob: "readonly",
        Math: "readonly",
        Number: "readonly",
        Date: "readonly",
        JSON: "readonly",
        Array: "readonly",
        Object: "readonly",
        String: "readonly",
        parseInt: "readonly",
        parseFloat: "readonly",
        isNaN: "readonly",
        Event: "readonly",
        HTMLElement: "readonly",
        SVGElement: "readonly",
        DOMParser: "readonly",
        Blob: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        // External globals from cities.js
        cityClimateData: "readonly",
        GISS_GLOBAL_ANOMALY: "readonly",
        CITY_SOURCES: "readonly",
        // AdSense
        adsbygoogle: "writable",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { varsIgnorePattern: "^[a-z].*" }],
      "no-undef": "error",
      "no-redeclare": "off",  // functions are global via top-level declarations
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "warn",
      "no-constant-condition": "warn",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-extra-semi": "warn",
      "no-irregular-whitespace": "error",
      "no-unexpected-multiline": "error",
      "valid-typeof": "error",
      "eqeqeq": ["warn", "smart"],
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-script-url": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-throw-literal": "warn",
      "no-useless-escape": "warn",
      "no-fallthrough": "warn",
      "no-case-declarations": "warn",
    },
  },
];
